<?php

namespace ContainerXlI8hXV;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCharacterResetCommand_LazyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.App\Command\CharacterResetCommand.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/LazyCommand.php';

        return $container->privates['.App\\Command\\CharacterResetCommand.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('app:character:reset', [], 'Reset or create a new player character', false, #[\Closure(name: 'App\\Command\\CharacterResetCommand')] fn (): \App\Command\CharacterResetCommand => ($container->privates['App\\Command\\CharacterResetCommand'] ?? $container->load('getCharacterResetCommandService')));
    }
}
