<?php

namespace ContainerXlI8hXV;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCharacterResetCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\CharacterResetCommand' shared autowired service.
     *
     * @return \App\Command\CharacterResetCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/src/Command/CharacterResetCommand.php';

        $container->privates['App\\Command\\CharacterResetCommand'] = $instance = new \App\Command\CharacterResetCommand(($container->services['doctrine.orm.default_entity_manager'] ?? $container->load('getDoctrine_Orm_DefaultEntityManagerService')));

        $instance->setName('app:character:reset');
        $instance->setDescription('Reset or create a new player character');

        return $instance;
    }
}
