<?php

namespace ContainerLnSZoP6;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCombatCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\CombatCommand' shared autowired service.
     *
     * @return \App\Command\CombatCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/src/Command/CombatCommand.php';

        $container->privates['App\\Command\\CombatCommand'] = $instance = new \App\Command\CombatCommand(($container->services['doctrine.orm.default_entity_manager'] ?? $container->load('getDoctrine_Orm_DefaultEntityManagerService')));

        $instance->setName('app:combat');
        $instance->setDescription('Add a short description for your command');

        return $instance;
    }
}
