<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXlI8hXV\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXlI8hXV/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXlI8hXV.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXlI8hXV\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXlI8hXV\App_KernelDevDebugContainer([
    'container.build_hash' => 'XlI8hXV',
    'container.build_id' => '1299bd1b',
    'container.build_time' => 1743259224,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXlI8hXV');
