<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container7bFoZyH\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container7bFoZyH/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container7bFoZyH.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container7bFoZyH\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container7bFoZyH\App_KernelDevDebugContainer([
    'container.build_hash' => '7bFoZyH',
    'container.build_id' => 'e822880f',
    'container.build_time' => 1742922793,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'Container7bFoZyH');
